services:
  web-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - /Users/onsahin/Library/Application\ Support/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /Users/onsahin/Library/Application\ Support/ASP.NET/Https:/root/.aspnet/https:ro